/**
 * Centralized generated/artifact detection.
 *
 * This module is intentionally lightweight and synchronous because it is used by
 * hot-path source collection and dispatch role detection. It combines cheap
 * path/name heuristics with optional header inspection for common generated-code
 * banners.
 */

import * as fs from "node:fs";
import * as path from "node:path";

const DEFAULT_HEADER_BYTES = 4096;

const GENERATED_DIR_NAMES = new Set([
	"generated",
	"__generated__",
	"codegen",
	"__codegen__",
	"generated-sources",
	"generated_sources",
	"openapi-generated",
	".openapi-generator",
]);

const GENERATED_HEADER_PATTERNS = [
	/@generated\b/i,
	/@ts-nocheck\b/i,
	/\bcode generated\b/i,
	/\bdo not edit\b/i,
	/\bautomatically generated\b/i,
	/\bthis file was generated\b/i,
	/\bgenerated by protoc\b/i,
	/\bgenerated by graphql-code-generator\b/i,
	/\bgenerated by openapi-generator\b/i,
	/\bgenerated by swagger codegen\b/i,
];

// Package-manager lockfiles are generated, never hand-written source — and
// often huge (a 10MB package-lock.json is unremarkable). Broadened enumeration
// (#894) made the .json/.yaml ones visible to project-wide walks; filtering
// them here (the generated-file authority) removes them from every collector
// at once. Compared lowercased, like GENERATED_DIR_NAMES.
const LOCKFILE_NAMES = new Set([
	"package-lock.json",
	"packages.lock.json",
	"npm-shrinkwrap.json",
	"pnpm-lock.yaml",
	"yarn.lock",
	"bun.lock",
	"cargo.lock",
	"composer.lock",
	"gemfile.lock",
	"poetry.lock",
	"uv.lock",
	"go.sum",
]);

const GENERATED_FILE_PATTERNS = [
	/(^|[._-])generated([._-]|$)/i,
	/(^|[._-])gen([._-])/i,
	/_generated\.(go|rs|py|rb|java|kt|ts|tsx|js|jsx|mjs|cjs)$/i,
	/_gen\.(go|rs|py|rb|java|kt|ts|tsx|js|jsx|mjs|cjs)$/i,
	/\.pb\.(go|ts|tsx|js|jsx|mjs|cjs)$/i,
	/_pb2(_grpc)?\.py$/i,
	/\.sql\.(go|ts|js)$/i,
	/_sqlc\.go$/i,
	/\.g\.([jt]sx?|mjs|cjs|rs|go)$/i,
	/\.min\.(js|mjs|cjs|css)$/i,
	/\.(bundle|chunk)\.(js|mjs|cjs|css)$/i,
];

const DECLARATION_FILE_PATTERNS = [/\.d\.ts$/i, /\.d\.mts$/i, /\.d\.cts$/i];

export interface GeneratedArtifactOptions {
	/** Optional file content or prefix. When omitted, content markers are skipped. */
	content?: string;
	/** Read a small file prefix to detect generated-code banners. */
	readContentHeader?: boolean;
	/** Number of bytes to read when readContentHeader is true. */
	maxHeaderBytes?: number;
	/** Treat declaration stubs (.d.ts/.d.mts/.d.cts) as artifacts. */
	includeDeclarations?: boolean;
}

function pathSegments(filePath: string): string[] {
	return path
		.normalize(filePath)
		.split(/[\\/]+/)
		.filter(Boolean);
}

export function isGeneratedArtifactDirectoryName(dirName: string): boolean {
	return GENERATED_DIR_NAMES.has(dirName.trim().toLowerCase());
}

export function isDeclarationFile(filePath: string): boolean {
	const base = path.basename(filePath).toLowerCase();
	return DECLARATION_FILE_PATTERNS.some((pattern) => pattern.test(base));
}

/**
 * STRONG evidence a path is generated/artifact output: it lives under a
 * directory segment that itself looks generated (`generated/`, `codegen/`,
 * …) or its basename is a known package-manager lockfile. Both are treated
 * as conclusive — no content-probe escape hatch (#1107 phase 2) applies to
 * either. A lockfile is never hand-written; a generated-dir SEGMENT match
 * here only fires for callers that check a single path without having
 * walked (directory-level pruning already removes the walk-time case in
 * `shouldRecurseIntoDir`, so this branch is effectively a belt-and-braces
 * check for non-walk callers like `file-role.ts` and `project-scan-policy.ts`).
 */
function hasStrongGeneratedArtifactPath(filePath: string): boolean {
	const segments = pathSegments(filePath);
	const dirSegments = segments.slice(0, -1);
	if (
		dirSegments.some((segment) => isGeneratedArtifactDirectoryName(segment))
	) {
		return true;
	}

	const base = path.basename(filePath);
	return LOCKFILE_NAMES.has(base.toLowerCase());
}

/**
 * WEAK evidence: the basename alone matches a generated-file NAME pattern
 * (e.g. `gen.ts`, `foo_generated.go`, `bar.min.js`). Unlike the strong path
 * check above, a name-only match is not conclusive — a hand-written file can
 * innocently contain "gen" in its name. #1107 phase 2's content-probe escape
 * hatch (see `classifyGeneratedOrArtifact`) requires corroborating evidence
 * (a generated-code header) before treating a WEAK-only match as an artifact.
 */
function hasWeakGeneratedFileNamePattern(filePath: string): boolean {
	const base = path.basename(filePath);
	return GENERATED_FILE_PATTERNS.some((pattern) => pattern.test(base));
}

function hasGeneratedArtifactContent(content: string): boolean {
	const header = content.slice(0, DEFAULT_HEADER_BYTES);
	return GENERATED_HEADER_PATTERNS.some((pattern) => pattern.test(header));
}

// Memoize the generated-banner verdict per (path, mtimeMs, size, maxBytes).
// The 4 KB header read (openSync + readSync + closeSync) is ~70% of the
// per-file cost in `collectSourceFiles`, and the same files are re-scanned by
// multiple background scanners (todo, project-diagnostics, language-profile)
// every session/turn. Keying on mtime+size makes the memo self-invalidating:
// an edited file misses the cache and is re-read. A single stat replaces the
// open/read/close on a hit. Bounded to avoid unbounded growth on giant repos.
const HEADER_VERDICT_MEMO_CAP = 50_000;
const headerVerdictMemo = new Map<string, boolean>();

/** Test-only: drop the header-verdict memo so fixtures don't leak across cases. */
export function _resetGeneratedArtifactCaches(): void {
	headerVerdictMemo.clear();
}

function readFileHeader(
	filePath: string,
	maxBytes = DEFAULT_HEADER_BYTES,
): string | undefined {
	let fd: number | undefined;
	try {
		fd = fs.openSync(filePath, "r");
		const buffer = Buffer.alloc(Math.max(0, maxBytes));
		const bytesRead = fs.readSync(fd, buffer, 0, buffer.length, 0);
		return buffer.toString("utf8", 0, bytesRead);
	} catch {
		return undefined;
	} finally {
		if (fd !== undefined) {
			try {
				fs.closeSync(fd);
			} catch {
				/* ignore close errors */
			}
		}
	}
}

/**
 * Memoized form of "does this file's header contain a generated-code banner?".
 * Returns `false` when the file cannot be stat'd/read (same fallback as the
 * inline read path). Keyed on path + mtime + size so edits invalidate it.
 */
function fileHeaderLooksGenerated(filePath: string, maxBytes: number): boolean {
	let key: string;
	try {
		const st = fs.statSync(filePath);
		key = `${st.mtimeMs}:${st.size}:${maxBytes}:${filePath}`;
	} catch {
		return false;
	}
	const cached = headerVerdictMemo.get(key);
	if (cached !== undefined) return cached;
	const header = readFileHeader(filePath, maxBytes);
	const verdict =
		header !== undefined && hasGeneratedArtifactContent(header);
	if (headerVerdictMemo.size >= HEADER_VERDICT_MEMO_CAP) {
		headerVerdictMemo.clear();
	}
	headerVerdictMemo.set(key, verdict);
	return verdict;
}

/**
 * Verdict of {@link classifyGeneratedOrArtifact}:
 *  - `"generated"`: confirmed generated/artifact output — skip it. Either a
 *    STRONG path match (generated dir segment, lockfile), an explicit
 *    declaration-file opt-in, a confirmed generated-code content header, or
 *    (only when no header probe was possible/enabled) a WEAK name-only
 *    match falling back to the pre-#1107-phase-2 trust-the-name behavior.
 *  - `"override"`: #1107 phase 2's content-probe escape hatch fired — a WEAK
 *    name-only match (e.g. `gen.ts`) that a content-header probe did NOT
 *    confirm. Kept, not skipped; callers that track observability should
 *    count this distinctly from a genuine `"clean"` (never-flagged) file so
 *    the heuristic's rescues stay visible.
 *  - `"clean"`: no evidence at all — never matched any heuristic.
 */
export type GeneratedArtifactVerdict = "generated" | "override" | "clean";

/**
 * The full verdict behind {@link isGeneratedOrArtifact}'s boolean, exposing
 * the #1107 phase 2 content-probe escape hatch: a WEAK name-only match (see
 * {@link hasWeakGeneratedFileNamePattern}) is no longer skipped on the name
 * alone — it additionally requires a generated-code header in the first few
 * KB (`hasGeneratedArtifactContent`/`fileHeaderLooksGenerated`) before being
 * treated as an artifact. Evidence check order is cheapest-first: STRONG
 * path (dir segment/lockfile, no filesystem probe) → declaration opt-in →
 * content/header probe, so the (often already-open) file read only happens
 * for the WEAK-match case that actually needs it.
 *
 * Evidence class (a) from the issue — "does a higher-precedence hand-written
 * source SIBLING exist?" — is deliberately NOT re-implemented here: it is
 * `source-filter.ts`'s `findSourceSibling`/`isBuildArtifact` (this module has
 * no filesystem-sibling-probe cache, and `source-filter.ts` already imports
 * this module, so adding a reverse import would be circular). Both call
 * sites that matter (`classifyEntry`, `filterSourceFiles` in
 * `source-filter.ts`) already probe for a sibling BEFORE reaching this
 * function and short-circuit on a hit, so by the time this function runs for
 * those callers evidence (a) has already come back negative. Non-walk
 * callers with no upstream sibling probe (`file-role.ts`'s content-based
 * check, `project-scan-policy.ts`'s single-path `shouldSkipProjectPath`)
 * evaluate evidence (b) only — a documented, narrower guarantee than the
 * walk path's.
 *
 * Tradeoff (documented per the issue): when NEITHER piece of evidence
 * confirms a WEAK name match, the file is KEPT. This can rescue a real
 * headerless generated file with no source twin into a walk/graph/index that
 * previously silently dropped it — accepted per #1107: a false-KEEP (an
 * agent sees one extra file it must itself judge) is strictly less harmful
 * than a silent false-DROP (a real file invisibly never analyzed at all).
 */
export function classifyGeneratedOrArtifact(
	filePath: string,
	options: GeneratedArtifactOptions = {},
): GeneratedArtifactVerdict {
	if (hasStrongGeneratedArtifactPath(filePath)) return "generated";
	if (options.includeDeclarations && isDeclarationFile(filePath)) {
		return "generated";
	}

	const weakNameMatch = hasWeakGeneratedFileNamePattern(filePath);

	if (options.content !== undefined) {
		if (hasGeneratedArtifactContent(options.content)) return "generated";
		return weakNameMatch ? "override" : "clean";
	}

	if (options.readContentHeader) {
		if (
			fileHeaderLooksGenerated(
				filePath,
				options.maxHeaderBytes ?? DEFAULT_HEADER_BYTES,
			)
		) {
			return "generated";
		}
		return weakNameMatch ? "override" : "clean";
	}

	// No content/header probe was supplied or enabled: there is no cheap way
	// to evaluate evidence (b) here, so a WEAK name match falls back to the
	// pre-#1107-phase-2 behavior (trust the name, skip it) rather than
	// silently activating the escape hatch for callers that opted out of the
	// probe for performance. The escape hatch only activates when a header
	// probe actually ran and did not confirm.
	return weakNameMatch ? "generated" : "clean";
}

export function isGeneratedOrArtifact(
	filePath: string,
	options: GeneratedArtifactOptions = {},
): boolean {
	return classifyGeneratedOrArtifact(filePath, options) === "generated";
}
